### PR TITLE
Update package-list.json

### PR DESCRIPTION
**Pull request by AlephNotation**
Update package-list.json for https://github.com/hdresearch/mcp-shell and https://github.com/hdresearch/kips

MCP shell is a server that allows access to the user's shell. 

Kips is a personal data store MCP models can use to keep track of tasks, write notes, access auth creds, etc.

### CODE REVIEW

**Comment by matildepark** [comment]
To be clear, `kips` has a user-facing interface as well and is run as an MCP server via `npx kips serve` and requires an init with `npx kips` (though we could try to automate that in the `serve` command?).

**Comment by michaellatman** [comment]
What init does it require? Can you format the json and submit as two PRs so we can work each out individually. For the other mcp server does it require any environmental variables?

**Comment by matildepark** [comment]
`npx mcp-shell` works normally. Neither need env vars. I just updated `kips` to not need an init. So both can be run from Claude with `npx -y [name]` now.

**Comment by michaellatman** [comment]
Perfect. Can you just reindent the JSON and we can merge? Thanks for the contribution!

**Comment by matildepark** [comment]
Wait, sorry, I misspoke, see previous comment edit.

**Comment by michaellatman** [comment]
Sounds like we'd need more work on the helper system within mcp-get to support kips in that case. But we can merge the other one for sure.

**Pull request merged**
