### PR TITLE
Add airtable-mcp-server to package-list.json

### PR DESCRIPTION
**Pull request by domdomegg**

### CODE REVIEW

**Comment by michaellatman** [comment]
Hey there, are there any required environmental variables? If so, can you add them to the helpers.ts.

**Comment by domdomegg** [comment]
No **required** environment variables. Users must either provide the API key:
- on the command line (takes priority over env); or
- as an environment variable (AIRTABLE_API_KEY).

**Comment by michaellatman** [comment]
Great! could you add that environmental variable to the helpers so that MCP get automatically uses it (either auto detected or prompted from the user)

**Comment by domdomegg** [comment]
Sure, updated and ready for review ✅

**Comment by michaellatman** [comment]
Merged thanks!

**Comment by michaellatman** [comment]
https://mcp-get.com/packages/airtable-mcp-server

**Pull request merged**
